# Generated by Django 4.2.2 on 2023-06-21 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'titulo',
                    models.CharField(max_length=50, verbose_name='Titulo'),
                ),
                ('slug', models.SlugField(max_length=55, verbose_name='Slug')),
                (
                    'categoria',
                    models.CharField(max_length=50, verbose_name='Categoria'),
                ),
                ('conteudo', models.TextField(verbose_name='Conteudo')),
                (
                    'criado_em',
                    models.DateField(
                        auto_now_add=True, verbose_name='Criado Em'
                    ),
                ),
                (
                    'atualizado_em',
                    models.DateField(
                        auto_now=True, verbose_name='Atualizado Em'
                    ),
                ),
                (
                    'publicado',
                    models.BooleanField(
                        default=False, verbose_name='Publicado'
                    ),
                ),
                (
                    'autor',
                    models.ForeignKey(
                        blank=True,
                        default=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Autor',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Lição',
                'verbose_name_plural': 'Lições',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'criado_em',
                    models.DateField(
                        auto_now_add=True, verbose_name='Criado Em'
                    ),
                ),
                (
                    'lesson',
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='classroom.lesson',
                        verbose_name='Lesson',
                    ),
                ),
                (
                    'usuario',
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Usuario',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'conteudo',
                    models.CharField(max_length=100, verbose_name='Comentario'),
                ),
                (
                    'criado_em',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Criado Em'
                    ),
                ),
                (
                    'lesson',
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='classroom.lesson',
                        verbose_name='Lesson',
                    ),
                ),
                (
                    'usuario',
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Usuario',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-criado_em'],
            },
        ),
    ]
